#!/bin/sh

cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # run functions

runApplication blockMesh
touch post.foam

#------------------------------------------------------------------------------
