#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # run functions

# copy mesh
cp -r /home/openfoam/run/blockMesh_ref_2/constant/polyMesh constant/

# run simulation
ln -s /home/output/rise_vel_CB4.ts .
ln -s /home/output/rad_CB4.ts .
ln -s /home/output/tv_CB4.ts .
runApplication decomposePar
cp -r 0.orig 0
restore0Dir -processor
runParallel $(getApplication)
runApplication reconstructPar

# post processing
postProcess -func singleGraph
calcSh -patch bubble -field s1 &> /dev/null
calcSh -patch bubble -field s2 &> /dev/null
calcSh -patch bubble -field s3 &> /dev/null
touch post.foam

#------------------------------------------------------------------------------
